add-clear-completed-button functionality
devlarabar/listify pull request #10
Opened 2023-06-01 20:19 UTC by AhmedHHamdy

## Description
This pull request adds the functionality to clear completed tasks by introducing a "Clear Completed" button. The button will appear whenever there are tasks, If there are no tasks available, the button will be hidden to maintain a cleaner user interface.

## Related Issue(s)
Closes #3 

## Additional Notes
My aim is to enhance the functionality to display the "Clear Completed" button only when there are completed tasks expected in the future. This would provide a cleaner interface by showing the button only when necessary.

2023-06-02 16:21 UTC, eva-lng requested changes
Well written code, it's a nice concise way how to implement the functionality, it utilises really well the existing code. It was really easy for me to read and understand the changes.

One minor naming issue I noticed:
line 111: it would probably make more sense to call the new variable 'unfinishedTasks' or something similar, since you filter out the completed tasks and keep the unfinished ones, it would make it more intuitive to read

2023-06-02 17:29 UTC, AhmedHHamdy commented
Thank you for pointing that out. Really, I should pay more attention to names. I definitely passed by it.

2023-06-04 12:41 UTC, eva-lng approved these changes

2023-06-05 19:01 UTC, devlarabar approved these changes

2023-06-05 19:02 UTC, merged